---

test:
  script:
    # normal test
    - MOLECULE_ZSH_USER=root molecule --debug test

    # test for other zsh_user
    - molecule create
    - docker exec -i ansible-role-zsh useradd testuser --create-home
    - MOLECULE_ZSH_USER=testuser molecule --debug converge
    - molecule destroy
