---
language: python
python: "2.7"
sudo: required
services:
  - docker

before_install:
  - docker --version || true
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  - docker --version || true
install:
  - pip install molecule docker
before_script:
  - export MOLECULE_APTPROXY_PATH="$PWD/00aptproxy" && touch "$MOLECULE_APTPROXY_PATH"
script:
  # normal test
  - MOLECULE_ZSH_USER=root molecule test

  # test for other zsh_user
  - molecule create
  - docker exec -i ansible-role-zsh-ubuntu-1604 useradd testuser --create-home
  - docker exec -i ansible-role-zsh-centos-7 useradd testuser --create-home
  - MOLECULE_ZSH_USER=testuser molecule converge
  - molecule destroy

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/