---

language: python
python: "2.7"
sudo: required
services:
  - docker

install: pip install molecule docker-py
script:
  - export MOLECULE_APTPROXY_PATH="$PWD/00aptproxy" && touch "$MOLECULE_APTPROXY_PATH"

  # normal test
  - MOLECULE_ZSH_USER=root molecule --debug test

  # test for other zsh_user
  - molecule create
  - docker exec -i ansible-role-zsh-ubuntu useradd testuser --create-home
  - docker exec -i ansible-role-zsh-centos useradd testuser --create-home
  - MOLECULE_ZSH_USER=testuser molecule --debug converge
  - molecule destroy

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/