---

- name: Check zsh version
  shell: "zsh --version | cut -d ' ' -f2"
  register: zsh_register_version
  changed_when: false
  tags: configure

- name: Check commands exists
  command: "which {{ item.command }}"
  with_items: "{{ zsh_antigen_bundles }}"
  failed_when: false
  changed_when: false
  when: item.command is defined
  register: zsh_register_commands_exists

- name: Write .zshrc config
  template:
    src: zshrc.j2
    dest: "{{ zsh_user_config }}"
    owner: "{{ zsh_user }}"
    group: "{{ zsh_user_group }}"
    backup: yes

- name: Set zsh as default shell
  user:
    name: "{{ zsh_user }}"
    shell: /bin/zsh
