---

- name: Write .zshrc config
  template:
    src: zshrc.j2
    dest: "{{ zsh_user_config }}"
    owner: "{{ zsh_user }}"
    group: "{{ zsh_user_group }}"

- name: Set zsh as default shell
  user:
    name: "{{ zsh_user }}"
    shell: /bin/zsh
