---

- name: Clone antigen
  git:
    repo: https://github.com/zsh-users/antigen.git
    dest: "{{ zsh_antigen_path }}/antigen"
    version: "{{ zsh_antigen_version }}"
  become: yes
  become_user: "{{ zsh_user }}"

# TODO: global install?
- name: Download fzf
  unarchive:
    src: "{{ zsh_fzf_url }}"
    dest: /usr/local/bin
    remote_src: yes
    creates: /usr/local/bin/fzf

#- name: Clone fzf plugin
#  git:
#    repo: https://github.com/junegunn/fzf.git
#    dest: "{{ zsh_custom_path }}/plugins/fzf"
#    version: master
#  when: "'fzf-zsh' in zsh_plugins"
#
#- name: Install fzf
#  command: "{{ zsh_custom_path }}/plugins/fzf/install --key-bindings --no-completion --no-update-rc"
#  args:
#    creates: "{{ zsh_custom_path }}/plugins/fzf/bin/fzf"
#  when: "'fzf-zsh' in zsh_plugins"
#
- name: Set directory permissions
  file:
    name: "{{ zsh_antigen_path }}"
    owner: "{{ zsh_user }}"
    group: "{{ zsh_user_group }}"
    recurse: yes
  changed_when: false
