---
- name: Install zsh, git, wget
  homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - zsh
    - git
    - wget

- name: Install tmux
  homebrew:
    name: tmux
    state: present
  when: "'tmux' in zsh_plugins"
