---

- name: Install zsh, git, wget
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - zsh
    - git
    - wget

- name: Clone antigen
  git:
    repo: https://github.com/zsh-users/antigen.git
    dest: "{{ zsh_antigen_path }}/antigen"
    version: "{{ zsh_antigen_version }}"
  become: yes
  become_user: "{{ zsh_user }}"

- name: Check fzf installed
  command: which fzf
  changed_when: false
  failed_when: false
  register: zsh_register_fzf_command

- name: Download fzf
  unarchive:
    src: "{{ zsh_fzf_url }}"
    dest: /usr/local/bin
    remote_src: yes
    creates: /usr/local/bin/fzf
  become: yes
  when: zsh_register_fzf_command.rc == 1

- name: Set directory permissions
  file:
    name: "{{ zsh_antigen_path }}"
    owner: "{{ zsh_user }}"
    group: "{{ zsh_user_group }}"
    recurse: yes
  changed_when: false
