---
# it will fail, but it install all bundles for user
- name: Install antigen bundles
  command: "/bin/zsh {{ zsh_user_config }}"
  become: yes
  become_user: "{{ zsh_user }}"
  changed_when: false
  failed_when: false

#- name: Install fzf
#  command: "{{ zsh_antigen_fzf_path }}/install --key-bindings --no-completion --no-update-rc"
#  args:
#    creates: "{{ zsh_antigen_fzf_path }}/bin/fzf"
#  when: "'junegunn/fzf' in zsh_antigen_bundles"
