---
- name: Reset antigen cache
  command: "/bin/zsh {{ zsh_user_config }} -c 'source ~/.antigen/antigen/antigen.zsh; antigen reset'"
  become: yes
  become_user: "{{ zsh_user }}"
  changed_when: false
  failed_when: false

# it will fail, but it install all bundles for user
- name: Update antigen bundles
  command: "/bin/zsh {{ zsh_user_config }} -c 'source ~/.antigen/antigen/antigen.zsh; antigen update'"
  become: yes
  become_user: "{{ zsh_user }}"
  changed_when: false
  failed_when: false
